name: pushler_core
description: Working with push notifications using the Pushler API and Firebase messaging.
version: 0.0.1
homepage: https://github.com/data-prime/pushler-flutter-core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^2.1.0
  dio: ^4.0.0
  rxdart: ^0.27.1
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.6
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  lints: ^1.0.1