name: pushler_core
description: Working with push notifications using the Pushler API and Firebase messaging.
version: 0.0.1
homepage: https://github.com/data-prime/pushler-flutter-core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.2
  dio: ^4.0.4
  rxdart: ^0.27.3
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  json_annotation: ^4.4.0
  freezed: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  lints: ^1.0.1